### ISSUE TITLE
Implement State Space Models (ETS).

### ISSUE THREAD

**Issue by hasanemirakin** [odtuyzt/time-series-analysis#11]
Implement the different ETS models.

-https://otexts.com/fpp2/ets.html(from chapter 7.5 to 7.7 contains the explanations and informations needed)

**Comment by hasanemirakin** [comment]
ETS Models ETS(A,N,N) and ETS(M,N,N) was implemented. For the full table of ETS models: https://otexts.com/fpp2/ets.html#tab:ssm

**Comment by hasanemirakin** [comment]
I will implement E(A, Ad, M) and E(M,Ad,M)

**Comment by AlperenOvak** [comment]
I will implement E(A, N, A) and E(M,N,A).

**Comment by muguryalcin** [comment]
I will implement E(A,A,A) and E(M,A,A).

**Comment by kilavuza** [comment]
I will implement E(M, A, N) and E(M, N, A).

**Comment by hasanemirakin** [comment]
I have reached some conclusions as a result of some research I want to share. The results of the ETS models we implement will most likely be very far off when compared to statsmodels. This is due to our implementation not having any parameter initialization functions. This leads to (in my case) some components having very large values. So, focus on implementing the fitting and forecasting equations for now. I will notify when the initialization functions are implemented.

**Comment by hasanemirakin** [comment]
Models Left:
-E(A,N,M)
-E(A,A,M)
-E(M,N,M)
-E(M,A,M)

**Comment by AlperenOvak** [comment]
I will implement E(A, N, M)

**Comment by hasanemirakin** [comment]
I will implement ETS(A,A,M) and ETS(M,A,M)

**Comment by hasanemirakin** [comment]
All ETS models are either implemented or in progress of implementation.
